<?php

// ini_set('display_errors','on');
// error_reporting(E_ALL);
// Implements hook_menu -> iig zo lang drush nog niet werkt

function spafdimport_menu() {

	$items = array();

	$items['admin/config/sp/afdimport-run'] = array(
		'title'            => 'Afdelingsimport uitvoeren',
		'type'             => MENU_CALLBACK,
		'page callback'    => 'spafdimport_afdelingen',
		'access arguments' => array('access administration pages'),
		'file'             => 'spafdimport.inc',
	);

	return $items;
}
